apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "terraria.fullname" . }}
  {{- include "terraria.namespace" . | nindent 2 }}
  labels:
    {{- include "terraria.labels" . | nindent 4 }}
data:
  serverconfig.txt: |
    port=7777
    upnp=0
    priority=1
    world={{ tpl .Values.world.name . }}.wld
    worldname={{ tpl .Values.world.name . }}
    {{- $worldsize := 0 }}
    {{- with .Values.world.size }}
    {{- if eq . "small" }}
      {{- $worldsize = 1 }}
    {{- else if eq . "medium" }}
      {{- $worldsize = 2 }}
    {{- else if eq . "large" }}
      {{- $worldsize = 3 }}
    {{- else }}
      {{- fail (printf "world.size '%s' is invalid, must be one of: small, medium, large" $worldsize) }}
    {{- end }}
    {{- end }}
    autocreate={{ $worldsize }}
    {{- $difficulty := 0 }}
    {{- with .Values.world.difficulty }}
    {{- if eq . "classic" }}
      {{- $difficulty = 0 }}
    {{- else if eq . "expert" }}
      {{- $difficulty = 1 }}
    {{- else if eq . "master" }}
      {{- $difficulty = 2 }}
    {{- else if eq . "journey" }}
      {{- $difficulty = 3 }}
    {{- else }}
      {{- fail (printf "world.difficulty '%s' is invalid, must be one of: classic, expert, master, journey" $difficulty) }}
    {{- end }}
    {{- end }}
    difficulty={{ $difficulty }}
    maxplayers={{ .Values.server.maxPlayers.base }}
    worldrollbackstokeep={{ .Values.world.rollbacksToKeep }}
    language={{ .Values.server.language }}
    {{- if .Values.server.password }}
    password={{ .Values.server.password }}
    {{- end }}
    {{- if .Values.world.seed }}
    seed={{ .Values.world.seed }}
    {{- end }}
    slowliquids={{ int .Values.world.slowLiquids }}
    secure={{ int .Values.antiCheatProtection.enabled }}
