apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "terraria.fullname" . }}-wait-for-startup
  {{- include "terraria.namespace" . | nindent 2 }}
  labels:
    {{- include "terraria.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade,post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: {{ include "terraria.fullname" . }}-wait-for-startup
      labels:
        {{- include "terraria.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: wait-for-startup
          {{- include "terraria.toolsImage" . | nindent 10 }}
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          command:
            - sh
            - -c
            - |
              while true
              do
                {{ include "terraria.socatLivenessCommand" . }} && break
                sleep 2
              done
      restartPolicy: Never
