---

name: Bump
on:
  schedule:
    - cron: '30 3 * * 1'
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.BUMP_PAT }}
          fetch-depth: 0

      - name: Find new version
        run: echo "NEW_VERSION=$(curl -sL https://terraria.wiki.gg/wiki/Server | grep 'https://terraria.org/api/download/pc-dedicated-server/terraria-server-[0-9]\+.zip' | grep -o 'Terraria Server [0-9.-]\+' | command grep -o '[0-9.-]\+' | sort | tail -n1)" >> $GITHUB_ENV

      - name: Bump vanilla Dockerfile version
        run: 'sed -Ei "s/(^ARG VERSION=)[\d.-]+/\1\"${{ env.NEW_VERSION }}\"/" images/vanilla/Dockerfile'
      - name: Bump vanilla Chart.yaml appVersion
        run: 'sed -Ei "s/(^appVersion: ?)[\d.-]+/\1${{ env.NEW_VERSION }}/" charts/vanilla/Chart.yaml'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Bump vanilla Terraria Server to ${{ env.NEW_VERSION }}
          tagging_message: "v${{ env.NEW_VERSION }}"
